### ISSUE TITLE
Key.cs is missing

### ISSUE THREAD

**Issue by Futhark1988** [Rintagi/Low-Code-Development-Platform#2]
I would like to try this application but it won't even start without the Common3/Key.cs file.

**Comment by rintagi-team** [comment]
Hi Futhark1988, 

Thank you for raising your inquiry. Just git clone is not a complete setup; after the clone, please follow the following steps:
1. Ensure all the prerequisites are set up properly via the instructions at https://www.rintagi.com/Docs/site/Initial-Setup/index.html
2. Run the installer found in https://github.com/Rintagi/Low-Code-Development-Platform/tree/master/DeployExt to set up the database, etc. 
3. The mentioned key.cs is deliberately removed from the git repo to be re-created during the installer process.

Kindly let us know if you have any additional questions or participate in our community discussion channel at https://gitter.im/Rintagi/home.
